# Generated by Django 4.0.4 on 2022-04-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
        ('recipe', '0002_remove_reply_comment_remove_reply_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
