# Generated by Django 4.0.4 on 2022-05-02 19:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_category_delete_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
